# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcke" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "4b68cfc106153ef6de373e369d79679b029b32df51a7ee114ee471b9289247e6"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3670e5a5fe3366667c506b6b9968d2e4b899790543579edff35a5abc0d846915"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "503424bf75f385bdfc631d872dc86802292fee502e23077801980dcbd67c0849"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bec5cbbac220326d32908ae827ae3e42497fd6e535a520dc79c0dee5ae09db0f"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pcke"
  desc "Project Context & Knowledge Engine — long-term engineering memory for AI agents"
  homepage "https://github.com/jenaiz/pcke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcke"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcke"]
    end
  end

  # No zap stanza required

end
