# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcke" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "daa446328cd80c48d90cd84d0ab298bd296e7a45050a6fe1dc0173ebd22ad249"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8eed401f21ce431b685c467852b3be21447b23a2b4e5c261c3b3d2144e949e94"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "909a96ce7dc552458bec8a042de84e78c114e8f175d436a8e0ed6d4fd68120a9"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b201716a50180704f6044a2bd2350aa892925203af4e8008c9f93b50e316aae"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pcke"
  desc "Project Context & Knowledge Engine — long-term engineering memory for AI agents"
  homepage "https://github.com/jenaiz/pcke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcke"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcke"]
    end
  end

  # No zap stanza required

end
