# This file was generated by GoReleaser. DO NOT EDIT.
cask "pcke" do
  version "0.13.2"

  on_macos do
    on_arm do
      sha256 "9e937be017bf7b8c98b54f37bd2083c20192e56a8e2131ac6a94f88f7788179d"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "21829843bbbab688fd6a722203b54a8f7677741ab21b1061c4c36199447320cb"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b764ec8d1d7bc418f4f7e7f8cb522926cdcafa87c0affc79339b3535e675cde9"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "afb3e32918806687fedad34d8439e0f47656335ccac8e401b1bbc08775e3737f"
      url "https://github.com/jenaiz/pcke/releases/download/v#{version}/pcke_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pcke"
  desc "Project Context & Knowledge Engine — long-term engineering memory for AI agents"
  homepage "https://github.com/jenaiz/pcke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pcke"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pcke"]
    end
  end

  # No zap stanza required
end
