# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pcke < Formula
  desc "Project Context & Knowledge Engine — long-term engineering memory for AI agents"
  homepage "https://github.com/jenaiz/pcke"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jenaiz/pcke/releases/download/v1.2.1/pcke_1.2.1_darwin_amd64.tar.gz"
      sha256 "1856c2c901c4e83926b4a7805388d201b73e3610cc212673cac33a880757d28b"

      define_method(:install) do
        bin.install "pcke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jenaiz/pcke/releases/download/v1.2.1/pcke_1.2.1_darwin_arm64.tar.gz"
      sha256 "d526f4641fd73965a84564d176161c05489ed02af212ac81981e3f87d79ff086"

      define_method(:install) do
        bin.install "pcke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jenaiz/pcke/releases/download/v1.2.1/pcke_1.2.1_linux_amd64.tar.gz"
      sha256 "d85a07ef58a3f779bf6deee2b3320724e86906bd5e0691169f2b5a24847e8b9c"
      define_method(:install) do
        bin.install "pcke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jenaiz/pcke/releases/download/v1.2.1/pcke_1.2.1_linux_arm64.tar.gz"
      sha256 "a259be76c05e1ba817b62050c31c75bfa057399c48d47ce3fac1ea5748061b37"
      define_method(:install) do
        bin.install "pcke"
      end
    end
  end

  test do
    system bin/"pcke", "--version"
  end
end
